[appendix]
== Anchor Definitions

This appendix provides anchor targets for cross-references to base RISC-V ISA
definitions that are referenced in the AME specification.

=== CSRs

[#ame:doc:csr:amefflags]
amefflags::
  See the AME state chapter for details on the `amefflags` CSR.

[#ame:doc:csr:amenlen]
amenlen::
  See the RISC-V Privileged Specification for details on the `amenlen` CSR.

[#ame:doc:csr:amestatus]
amestatus::
  See the RISC-V Privileged Specification for details on the `amestatus` CSR.

[#ame:doc:csr:ameudsz]
ameudsz::
  See the RISC-V Privileged Specification for details on the `ameudsz` CSR.

[#ame:doc:csr:ame_scalar_dtype]
ame_scalar_dtype::
  See the RISC-V Privileged Specification for details on the `ame_scalar_dtype` CSR.

[#ame:doc:csr:amexsat]
amexsat::
  See the AME state chapter for details on the `amexsat` CSR.

[#ame:doc:csr:hedeleg]
hedeleg::
  See the RISC-V Privileged Specification for details on the `hedeleg` CSR.

[#ame:doc:csr:henvcfg]
henvcfg::
  See the RISC-V Privileged Specification for details on the `henvcfg` CSR.

[#ame:doc:csr:hgatp]
hgatp::
  See the RISC-V Privileged Specification for details on the `hgatp` CSR.

[#ame:doc:csr:hstatus]
hstatus::
  See the RISC-V Privileged Specification for details on the `hstatus` CSR.

[#ame:doc:csr:htinst]
htinst::
  See the RISC-V Privileged Specification for details on the `htinst` CSR.

[#ame:doc:csr:htval]
htval::
  See the RISC-V Privileged Specification for details on the `htval` CSR.

[#ame:doc:csr:mcause]
mcause::
  See the RISC-V Privileged Specification for details on the `mcause` CSR.

[#ame:doc:csr:medeleg]
medeleg::
  See the RISC-V Privileged Specification for details on the `medeleg` CSR.

[#ame:doc:csr:menvcfg]
menvcfg::
  See the RISC-V Privileged Specification for details on the `menvcfg` CSR.

[#ame:doc:csr:mepc]
mepc::
  See the RISC-V Privileged Specification for details on the `mepc` CSR.

[#ame:doc:csr:mideleg]
mideleg::
  See the RISC-V Privileged Specification for details on the `mideleg` CSR.

[#ame:doc:csr:mie]
mie::
  See the RISC-V Privileged Specification for details on the `mie` CSR.

[#ame:doc:csr:mip]
mip::
  See the RISC-V Privileged Specification for details on the `mip` CSR.

[#ame:doc:csr:misa]
misa::
  See the RISC-V Privileged Specification for details on the `misa` CSR.

[#ame:doc:csr:mstatus]
mstatus::
  See the RISC-V Privileged Specification for details on the `mstatus` CSR.

[#ame:doc:csr:mstatush]
mstatush::
  See the RISC-V Privileged Specification for details on the `mstatush` CSR.

[#ame:doc:csr:mtinst]
mtinst::
  See the RISC-V Privileged Specification for details on the `mtinst` CSR.

[#ame:doc:csr:mtval]
mtval::
  See the RISC-V Privileged Specification for details on the `mtval` CSR.

[#ame:doc:csr:mtval2]
mtval2::
  See the RISC-V Privileged Specification for details on the `mtval2` CSR.

[#ame:doc:csr:mtvec]
mtvec::
  See the RISC-V Privileged Specification for details on the `mtvec` CSR.

[#ame:doc:csr:satp]
satp::
  See the RISC-V Privileged Specification for details on the `satp` CSR.

[#ame:doc:csr:scause]
scause::
  See the RISC-V Privileged Specification for details on the `scause` CSR.

[#ame:doc:csr:sepc]
sepc::
  See the RISC-V Privileged Specification for details on the `sepc` CSR.

[#ame:doc:csr:samecfg]
samecfg::
  See <<ame-user-ownership-enable>> for details on the `samecfg` CSR.

[#ame:doc:csr:sstatus]
sstatus::
  See the RISC-V Privileged Specification for details on the `sstatus` CSR.

[#ame:doc:csr:stval]
stval::
  See the RISC-V Privileged Specification for details on the `stval` CSR.

[#ame:doc:csr:stvec]
stvec::
  See the RISC-V Privileged Specification for details on the `stvec` CSR.

[#ame:doc:csr:vsatp]
vsatp::
  See the RISC-V Privileged Specification for details on the `vsatp` CSR.

[#ame:doc:csr:vscause]
vscause::
  See the RISC-V Privileged Specification for details on the `vscause` CSR.

[#ame:doc:csr:vsepc]
vsepc::
  See the RISC-V Privileged Specification for details on the `vsepc` CSR.

[#ame:doc:csr:vsstatus]
vsstatus::
  See the RISC-V Privileged Specification for details on the `vsstatus` CSR.

[#ame:doc:csr:vstval]
vstval::
  See the RISC-V Privileged Specification for details on the `vstval` CSR.

[#ame:doc:csr:vstvec]
vstvec::
  See the RISC-V Privileged Specification for details on the `vstvec` CSR.

=== CSR Fields

[#ame:doc:csr_field:amefflags:NV]
amefflags.NV::
  See the AME state chapter for details on the `amefflags.NV` field.

[#ame:doc:csr_field:amefflags:DZ]
amefflags.DZ::
  See the AME state chapter for details on the `amefflags.DZ` field.

[#ame:doc:csr_field:amefflags:OF]
amefflags.OF::
  See the AME state chapter for details on the `amefflags.OF` field.

[#ame:doc:csr_field:amefflags:UF]
amefflags.UF::
  See the AME state chapter for details on the `amefflags.UF` field.

[#ame:doc:csr_field:amefflags:NX]
amefflags.NX::
  See the AME state chapter for details on the `amefflags.NX` field.

[#ame:doc:csr_field:amestatus:UN]
amestatus.UN::
  See the RISC-V Privileged Specification for details on the `amestatus.UN` field.

[#ame:doc:csr_field:amexsat:SAT]
amexsat.SAT::
  See the AME state chapter for details on the `amexsat.SAT` field.

[#ame:doc:csr_field:samecfg:UOE]
samecfg.UOE::
  See <<ame-user-ownership-enable>> for details on the `samecfg.UOE` field.

[#ame:doc:csr_field:henvcfg:ADUE]
henvcfg.ADUE::
  See the RISC-V Privileged Specification for details on the `henvcfg.ADUE` field.

[#ame:doc:csr_field:henvcfg:PBMTE]
henvcfg.PBMTE::
  See the RISC-V Privileged Specification for details on the `henvcfg.PBMTE` field.

[#ame:doc:csr_field:hgatp:MODE]
hgatp.MODE::
  See the RISC-V Privileged Specification for details on the `hgatp.MODE` field.

[#ame:doc:csr_field:hgatp:PPN]
hgatp.PPN::
  See the RISC-V Privileged Specification for details on the `hgatp.PPN` field.

[#ame:doc:csr_field:hstatus:GVA]
hstatus.GVA::
  See the RISC-V Privileged Specification for details on the `hstatus.GVA` field.

[#ame:doc:csr_field:hstatus:SPV]
hstatus.SPV::
  See the RISC-V Privileged Specification for details on the `hstatus.SPV` field.

[#ame:doc:csr_field:hstatus:SPVP]
hstatus.SPVP::
  See the RISC-V Privileged Specification for details on the `hstatus.SPVP` field.

[#ame:doc:csr_field:hstatus:VSXL]
hstatus.VSXL::
  See the RISC-V Privileged Specification for details on the `hstatus.VSXL` field.

[#ame:doc:csr_field:htinst:VALUE]
htinst.VALUE::
  See the RISC-V Privileged Specification for details on the `htinst.VALUE` field.

[#ame:doc:csr_field:htval:VALUE]
htval.VALUE::
  See the RISC-V Privileged Specification for details on the `htval.VALUE` field.

[#ame:doc:csr_field:mcause:CODE]
mcause.CODE::
  See the RISC-V Privileged Specification for details on the `mcause.CODE` field.

[#ame:doc:csr_field:mcause:INT]
mcause.INT::
  See the RISC-V Privileged Specification for details on the `mcause.INT` field.

[#ame:doc:csr_field:menvcfg:ADUE]
menvcfg.ADUE::
  See the RISC-V Privileged Specification for details on the `menvcfg.ADUE` field.

[#ame:doc:csr_field:menvcfg:PBMTE]
menvcfg.PBMTE::
  See the RISC-V Privileged Specification for details on the `menvcfg.PBMTE` field.

[#ame:doc:csr_field:mepc:PC]
mepc.PC::
  See the RISC-V Privileged Specification for details on the `mepc.PC` field.

[#ame:doc:csr_field:misa:H]
misa.H::
  See the RISC-V Privileged Specification for details on the `misa.H` field.

[#ame:doc:csr_field:misa:MXL]
misa.MXL::
  See the RISC-V Privileged Specification for details on the `misa.MXL` field.

[#ame:doc:csr_field:misa:S]
misa.S::
  See the RISC-V Privileged Specification for details on the `misa.S` field.

[#ame:doc:csr_field:misa:U]
misa.U::
  See the RISC-V Privileged Specification for details on the `misa.U` field.

[#ame:doc:csr_field:mstatus:MIE]
mstatus.MIE::
  See the RISC-V Privileged Specification for details on the `mstatus.MIE` field.

[#ame:doc:csr_field:mstatus:MPP]
mstatus.MPP::
  See the RISC-V Privileged Specification for details on the `mstatus.MPP` field.

[#ame:doc:csr_field:mstatus:MPRV]
mstatus.MPRV::
  See the RISC-V Privileged Specification for details on the `mstatus.MPRV` field.

[#ame:doc:csr_field:mstatus:MPV]
mstatus.MPV::
  See the RISC-V Privileged Specification for details on the `mstatus.MPV` field.

[#ame:doc:csr_field:mstatus:MXR]
mstatus.MXR::
  See the RISC-V Privileged Specification for details on the `mstatus.MXR` field.

[#ame:doc:csr_field:mstatus:SIE]
mstatus.SIE::
  See the RISC-V Privileged Specification for details on the `mstatus.SIE` field.

[#ame:doc:csr_field:mstatus:SPP]
mstatus.SPP::
  See the RISC-V Privileged Specification for details on the `mstatus.SPP` field.

[#ame:doc:csr_field:mstatus:SUM]
mstatus.SUM::
  See the RISC-V Privileged Specification for details on the `mstatus.SUM` field.

[#ame:doc:csr_field:mstatus:SXL]
mstatus.SXL::
  See the RISC-V Privileged Specification for details on the `mstatus.SXL` field.

[#ame:doc:csr_field:mstatus:UXL]
mstatus.UXL::
  See the RISC-V Privileged Specification for details on the `mstatus.UXL` field.

[#ame:doc:csr_field:mstatush:MPV]
mstatush.MPV::
  See the RISC-V Privileged Specification for details on the `mstatush.MPV` field.

[#ame:doc:csr_field:mtinst:VALUE]
mtinst.VALUE::
  See the RISC-V Privileged Specification for details on the `mtinst.VALUE` field.

[#ame:doc:csr_field:mtval2:VALUE]
mtval2.VALUE::
  See the RISC-V Privileged Specification for details on the `mtval2.VALUE` field.

[#ame:doc:csr_field:mtval:VALUE]
mtval.VALUE::
  See the RISC-V Privileged Specification for details on the `mtval.VALUE` field.

[#ame:doc:csr_field:mtvec:BASE]
mtvec.BASE::
  See the RISC-V Privileged Specification for details on the `mtvec.BASE` field.

[#ame:doc:csr_field:satp:MODE]
satp.MODE::
  See the RISC-V Privileged Specification for details on the `satp.MODE` field.

[#ame:doc:csr_field:satp:PPN]
satp.PPN::
  See the RISC-V Privileged Specification for details on the `satp.PPN` field.

[#ame:doc:csr_field:scause:CODE]
scause.CODE::
  See the RISC-V Privileged Specification for details on the `scause.CODE` field.

[#ame:doc:csr_field:scause:INT]
scause.INT::
  See the RISC-V Privileged Specification for details on the `scause.INT` field.

[#ame:doc:csr_field:sepc:PC]
sepc.PC::
  See the RISC-V Privileged Specification for details on the `sepc.PC` field.

[#ame:doc:csr_field:sstatus:UXL]
sstatus.UXL::
  See the RISC-V Privileged Specification for details on the `sstatus.UXL` field.

[#ame:doc:csr_field:stval:VALUE]
stval.VALUE::
  See the RISC-V Privileged Specification for details on the `stval.VALUE` field.

[#ame:doc:csr_field:stvec:BASE]
stvec.BASE::
  See the RISC-V Privileged Specification for details on the `stvec.BASE` field.

[#ame:doc:csr_field:vsatp:MODE]
vsatp.MODE::
  See the RISC-V Privileged Specification for details on the `vsatp.MODE` field.

[#ame:doc:csr_field:vsatp:PPN]
vsatp.PPN::
  See the RISC-V Privileged Specification for details on the `vsatp.PPN` field.

[#ame:doc:csr_field:vscause:CODE]
vscause.CODE::
  See the RISC-V Privileged Specification for details on the `vscause.CODE` field.

[#ame:doc:csr_field:vscause:INT]
vscause.INT::
  See the RISC-V Privileged Specification for details on the `vscause.INT` field.

[#ame:doc:csr_field:vsepc:PC]
vsepc.PC::
  See the RISC-V Privileged Specification for details on the `vsepc.PC` field.

[#ame:doc:csr_field:vsstatus:MXR]
vsstatus.MXR::
  See the RISC-V Privileged Specification for details on the `vsstatus.MXR` field.

[#ame:doc:csr_field:vsstatus:SPP]
vsstatus.SPP::
  See the RISC-V Privileged Specification for details on the `vsstatus.SPP` field.

[#ame:doc:csr_field:vsstatus:SUM]
vsstatus.SUM::
  See the RISC-V Privileged Specification for details on the `vsstatus.SUM` field.

[#ame:doc:csr_field:vsstatus:UXL]
vsstatus.UXL::
  See the RISC-V Privileged Specification for details on the `vsstatus.UXL` field.

[#ame:doc:csr_field:vstval:VALUE]
vstval.VALUE::
  See the RISC-V Privileged Specification for details on the `vstval.VALUE` field.

[#ame:doc:csr_field:vstvec:BASE]
vstvec.BASE::
  See the RISC-V Privileged Specification for details on the `vstvec.BASE` field.
