---
name: Release New ISA When Merging a PR

on:
  workflow_run:
    workflows: [RISC-V ISA Build]
    branches:
      - main
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/riscv/riscv-docs-base-container-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - run: echo The PR was successfully merged.

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build PDF
        id: build_files
        run: make pdf

      - name: Upload Zvame PDF
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: Zvame-0.1-${{ env.SHORT_SHA }}.pdf
          path: ${{ github.workspace }}/build/Zvame-0.1.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
        with:
          tag_name: riscv-isa-release-${{ env.SHORT_SHA }}-${{ env.CURRENT_DATE }}
          name: Release riscv-isa-release-${{ env.SHORT_SHA }}-${{ env.CURRENT_DATE }}
          draft: false
          prerelease: false
          make_latest: true
          generate_release_notes: true
          body: |
            This release was created by: ${{ github.event.sender.login }}
            Release of AME (Zvame) specification, built from commit ${{ env.SHORT_SHA }}, is now available.
          files: |
            ${{ github.workspace }}/build/Zvame-0.1.pdf
